#!/bin/sh
. "$(dirname "$0")/_/husky.sh"


if git diff --cached --name-only | grep --quiet "odd-platform-ui"
then
  cd odd-platform-ui && npm run pre-commit
else 
  echo "Skipping frontend tests"
  exit 0
fi
