version: 2
updates:
- package-ecosystem: npm
  directory: "/odd-platform-ui"
  schedule:
    interval: weekly
    time: "10:00"
    timezone: Europe/Moscow
  open-pull-requests-limit: 10
  versioning-strategy: increase-if-necessary
  labels:
    - "scope: frontend"
  ignore:
  - dependency-name: react-scripts
    versions:
    - 4.0.3
    - 5.0.0
  - dependency-name: lodash
    versions:
    - 4.17.21
  - dependency-name: react-json-tree
    versions:
    - 0.15.0
