name-template: 'v$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
template: |
  ## Changes
  $CHANGES
  ## Contributors
  $CONTRIBUTORS
  
exclude-labels:
  - 'skip-changelog'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    label: 'chore'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
autolabeler:
  - label: 'kind: documentation'
    files:
      - '*.md'
    branch:
      - '/docs{0,1}\/.+/'
      - '/gh-pages\/.+/'
  - label: 'kind: bug'
    branch:
      - '/fix\/.+/'
      - 'issues\/.+/'
      - 'issue\/.+/'
    title:
      - '/fix/i'
      - 'issues/i'
      - 'issue/i'
  - label: 'kind: enhancement'
    branch:
      - '/new\/.+/'
  - label: 'kind: feature'
    branch:
      - '/feature\/.+/'
