route:
  group_by: [ 'job' ]
  group_wait: 1s
  group_interval: 5m
  repeat_interval: 12h
  receiver: webhook
  routes:
    - receiver: webhook
      continue: true
receivers:
  - name: webhook
    webhook_configs:
      - url: 'http://host.docker.internal:8080/ingestion/alert/alertmanager'