receivers:
  otlp:
    protocols:
      grpc:

exporters:
  logging:
    loglevel: debug
  prometheusremotewrite:
    endpoint: "${PRW_ENDPOINT}"
    insecure: true

extensions:
  zpages:
    endpoint: 0.0.0.0:55679

service:
  extensions: [ zpages ]
  pipelines:
    metrics:
      receivers: [ otlp ]
      exporters: [ prometheusremotewrite ]