package org.opendatadiscovery.oddplatform.dto.activity;

public enum ActivityEventTypeDto {
    OWNERSHIP_CREATED,
    OWNERSHIP_UPDATED,
    OWNERSHIP_DELETED,
    TAGS_ASSOCIATION_UPDATED,
    DATA_ENTITY_CREATED,
    DATA_ENTITY_OVERVIEW_UPDATED,
    DATA_ENTITY_METADATA_UPDATED,
    DATA_ENTITY_SCHEMA_UPDATED,
    DATA_ENTITY_RELATION_UPDATED,
    TERM_ASSIGNED,
    TERM_ASSIGNMENT_DELETED,
    DESCRIPTION_UPDATED,
    CUSTOM_NAME_UPDATED,
    CUSTOM_METADATA_CREATED,
    CUSTOM_METADATA_UPDATED,
    CUSTOM_METADATA_DELETED,
    DATASET_FIELD_VALUES_UPDATED,
    DATASET_FIELD_INFORMATION_UPDATED,
    CUSTOM_GROUP_CREATED,
    CUSTOM_GROUP_UPDATED,
    CUSTOM_GROUP_DELETED;
}
