ALTER TABLE tag_to_data_entity
    ADD COLUMN IF NOT EXISTS external BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE label_to_dataset_field
    ADD COLUMN IF NOT EXISTS external BOOLEAN NOT NULL DEFAULT FALSE;