ALTER TABLE owner ALTER COLUMN created_at SET DEFAULT (NOW() AT TIME ZONE ('UTC'));
ALTER TABLE owner ALTER COLUMN updated_at SET DEFAULT (NOW() AT TIME ZONE ('UTC'));

ALTER TABLE namespace ALTER COLUMN created_at SET DEFAULT (NOW() AT TIME ZONE ('UTC'));
ALTER TABLE namespace ALTER COLUMN updated_at SET DEFAULT (NOW() AT TIME ZONE ('UTC'));

ALTER TABLE tag ALTER COLUMN created_at SET DEFAULT (NOW() AT TIME ZONE ('UTC'));
ALTER TABLE tag ALTER COLUMN updated_at SET DEFAULT (NOW() AT TIME ZONE ('UTC'));

ALTER TABLE label ALTER COLUMN created_at SET DEFAULT (NOW() AT TIME ZONE ('UTC'));
ALTER TABLE label ALTER COLUMN updated_at SET DEFAULT (NOW() AT TIME ZONE ('UTC'));

ALTER TABLE data_source ALTER COLUMN created_at SET DEFAULT (NOW() AT TIME ZONE ('UTC'));
ALTER TABLE data_source ALTER COLUMN updated_at SET DEFAULT (NOW() AT TIME ZONE ('UTC'));

ALTER TABLE dataset_version ALTER COLUMN created_at SET DEFAULT (NOW() AT TIME ZONE ('UTC'));

ALTER TABLE enum_value ALTER COLUMN created_at SET DEFAULT (NOW() AT TIME ZONE ('UTC'));
ALTER TABLE enum_value ALTER COLUMN updated_at SET DEFAULT (NOW() AT TIME ZONE ('UTC'));

ALTER TABLE token ALTER COLUMN created_at SET DEFAULT (NOW() AT TIME ZONE ('UTC'));
ALTER TABLE token ALTER COLUMN updated_at SET DEFAULT (NOW() AT TIME ZONE ('UTC'));

ALTER TABLE collector ALTER COLUMN created_at SET DEFAULT (NOW() AT TIME ZONE ('UTC'));
ALTER TABLE collector ALTER COLUMN updated_at SET DEFAULT (NOW() AT TIME ZONE ('UTC'));

ALTER TABLE term ALTER COLUMN created_at SET DEFAULT (NOW() AT TIME ZONE ('UTC'));
ALTER TABLE term ALTER COLUMN updated_at SET DEFAULT (NOW() AT TIME ZONE ('UTC'));

ALTER TABLE role ALTER COLUMN created_at SET DEFAULT (NOW() AT TIME ZONE ('UTC'));
ALTER TABLE role ALTER COLUMN updated_at SET DEFAULT (NOW() AT TIME ZONE ('UTC'));

ALTER TABLE activity ALTER COLUMN created_at SET DEFAULT (NOW() AT TIME ZONE ('UTC'));

ALTER TABLE owner_association_request ALTER COLUMN created_at SET DEFAULT (NOW() AT TIME ZONE ('UTC'));

ALTER TABLE policy ALTER COLUMN created_at SET DEFAULT (NOW() AT TIME ZONE ('UTC'));
ALTER TABLE policy ALTER COLUMN updated_at SET DEFAULT (NOW() AT TIME ZONE ('UTC'));

ALTER TABLE title ALTER COLUMN created_at SET DEFAULT (NOW() AT TIME ZONE ('UTC'));
ALTER TABLE title ALTER COLUMN updated_at SET DEFAULT (NOW() AT TIME ZONE ('UTC'));

ALTER TABLE alert_chunk ALTER COLUMN created_at SET DEFAULT (NOW() AT TIME ZONE ('UTC'));

ALTER TABLE alert ALTER COLUMN last_created_at SET DEFAULT (NOW() AT TIME ZONE ('UTC'));