name: Main branch Build
on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  images:
    runs-on: ubuntu-latest
    env:
      REGISTRY: 436866023604.dkr.ecr.eu-central-1.amazonaws.com
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Gradle
        env:
          GENERATE_SOURCEMAP: false
          JAVA_OPTS: "-Xms2048m -Xmx2048m"
        run: ./gradlew clean test --no-daemon 
