name: PR checkstyle
on:
  workflow_dispatch:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Set up JDK 13
        uses: actions/setup-java@v2
        with:
          java-version: '13'
          distribution: 'adopt'
      - name: Build with Gradle
        env:
          NODE_ENV: production
          GENERATE_SOURCEMAP: false
          CI: false
          JAVA_OPTS: "-Xms2048m -Xmx2048m"
        run: ./gradlew clean checkstyleMain checkstyleTest