name: PR build
on:
  workflow_dispatch:
  pull_request:
    types: [ 'opened', 'edited', 'reopened', 'synchronize' ]

permissions:
  checks: write
  pull-requests: write

jobs:
  run_tests:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
      - name: Cache local node_modules
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-platform-${{ hashFiles('**/build.gradle') }}
          restore-keys: |
            ${{ runner.os }}-platform-
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run tests
        env:
          GENERATE_SOURCEMAP: false
          CI: false
          JAVA_OPTS: "-Xms1G -Xmx1G"
        run: ./gradlew clean test ${{ github.event.inputs.buildOptions }}
      - name: Publish test reports
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: "odd-platform-api/build/test-results/**/*.xml"
          check_name: Test Results
          comment_mode: create new
